[package]
name = "apollo-cli"
version = "0.0.2"
authors = ["Apollo <opensource@apollographql.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "*"
failure = "*"
graphql-parser = { path = "../graphql-parser" }

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"
