[package]
name = "apollo-cli"
version = "0.0.2"
authors = ["Apollo <opensource@apollographql.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
console = "0.6.1"
failure = "*"
graphql-parser = { path = "../graphql-parser" }
log = { version = "0.4", features = ["std"] }
structopt = "*"
term_size = "0.3.0"
textwrap = "0.11.0"


[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"
