name: Publish

on:
  push:
    branches:
      - junk
    
jobs:
  publish:
    name: Publish workflow
    if: "contains(github.event.head_commit.message, 'release:')"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Publish to npm
        run: |
          RELEASE_VERSION=`npm pkg get version -w @apollo/composition|jq -r '.["@apollo/composition"]'`
          echo "starting the publish step" $RELEASE_VERSION
          npx changeset publish
          git push --follow-tags
        